### ISSUE TITLE
Multi-variant testing against Rails 6 and Rails 7

### ISSUE THREAD

**Issue by benjaminoakes** [doximity/super_spreader#17]
We support both Rails 6.x and Rails 7.x.  We should test against both in CI.

Please see https://github.com/doximity/super_spreader/pull/11#discussion_r1100834387 for more context

_This is a stub.  You can help by expanding it._

**Comment by TheMetalCode** [comment]
Addressed via https://github.com/doximity/super_spreader/pull/59
